### ISSUE TITLE
Cython and jinja2 should not always be installed

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#1]
I think that we might want to have a flag that indicates whether to install Cython and jinja2. Jinja2 is only required by the astropy core package, and Cython only by a small fraction of affiliated packages (+core).

**Comment by bsipocz** [comment]
isn't jinja required for the sphinx builds?

**Comment by astrofrog** [comment]
Ah that's possible, but what I mean is that we normally install it at the same time as Cython for the core package because of templates in the ERFA stuff. But otherwise we never need to install it explicitly (it might get installed when installing sphinx). So what I mean is that it should be treated as an additional dependency for the core package and not explicitly installed for affiliated packages.

By the way, I'm on gitter.im today in case you want to live-chat about any of this.

**Comment by bsipocz** [comment]
This is fixed now with the new env variables.
