### ISSUE TITLE
Introduce fall-back onto pip if conda doesn't have recent version

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#100]
Based on recent discussion in #97 #98 and on [gitter](https://gitter.im/astropy/astropy?at=576185c8dfb1d8aa45a3b700), we will need an option to fall back on altrnative ways of installing a package is the version available on conda is too old.

E.g. if a build asks for 'stable' astropy version (currently we have v1.2rc1), then it's not OK to install v0.3 or v0.4 or even v1.0.3 from conda, but should go instead pip install v1.1.2

**Comment by astrofrog** [comment]
@bsipocz - this is done, right?

**Comment by bsipocz** [comment]
Indeed!
