### ISSUE TITLE
Travis failing on sphinx stage and astropy lts python3.5

### ISSUE THREAD

**Issue by cmccully** [astropy/ci-helpers#105]
@bsipocz and @pllim 
I still have a couple of tests failing due to conda ci issues:
https://travis-ci.org/LCOGT/banzai/jobs/139364978

https://travis-ci.org/LCOGT/banzai/jobs/139364982

Fetching package metadata .............
Solving package specifications: ....
The following specifications were found to be in conflict:
  - astropy 1.0* -> numpy 1.10*|1.6*|1.7*|1.8*|1.9*
  - astropy 1.0* -> python 2.6*|2.7*|3.3*|3.4*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

The other builds pass: https://travis-ci.org/LCOGT/banzai/builds/139364970

Thanks for your help.

**Comment by astrofrog** [comment]
@cmccully - there is no conda package for Astropy 1.0 and Python 3.5, so this will likely cause some of the issues you are seeing.

cc @mwcraig

**Comment by cmccully** [comment]
Thanks @astrofrog. Any idea why the 2.7 version would be failing on the sphinx command? 

Solving package specifications: ....
The following specifications were found to be in conflict:
  - matplotlib !=1.5.1
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.

**Comment by astrofrog** [comment]
@cmccully - this is a known issue, and should be fixed later

**Comment by mwcraig** [comment]
@cmccully -- I gather you would like to be able to test the LTS astropy release on python 3.5? I've got a builder up and running, I can add this combination to the list.

Actually, if you have a few minutes, please fill this out: http://goo.gl/forms/MnL0IBtoTXVhMIuF3 (will send link out more broadly later today once I've got a couple of responses).

@astrofrog -- do we want conda builds of LTS available to users? Looks like continuum is not building them...

**Comment by cmccully** [comment]
Thanks @mwcraig and @astrofrog. @mwcraig I mostly was just hoping to have the CI work via the package template. I am most worried about Python 2.7 and 3.5 both with the latest stable version of astropy (though astropy 1.0 would be a good sanity check). I have filled out the form as requested.

**Comment by astrofrog** [comment]
@cmccully - the matplotlib failure should be fixed, you can restart builds now

**Comment by cmccully** [comment]
Thanks @astrofrog!

**Comment by astrofrog** [comment]
@bsipocz is to thank for the fix, not me :)

**Comment by cmccully** [comment]
Well then thanks @bsipocz !

**Comment by mwcraig** [comment]
@cmccully -- astropy LTS is now on astropy-ci-extras for python 3.5 and the versions of numpy that continuum provides (1.9 through 1.11)

**Comment by bsipocz** [comment]
@mwcraig - Thank you for building the LTS releases.

@cmccully - Could you please check whether the build now pass?

**Comment by cmccully** [comment]
Thanks @mwcraig! That does indeed fix the build @bsipocz. Thanks!

https://travis-ci.org/LCOGT/banzai/builds/139364970
