### ISSUE TITLE
Mixing stable and dev packages in PIP_DEPENDENCIES on AppVeyor

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#108]
On Travis, doing something like

```
PIP_DEPENDENCIES="pydicom https://github.com/glue-viz/glue/archive/master.zip"
```

is fine, but on AppVeyor, it results in the following error:

https://ci.appveyor.com/project/astrofrog/glue-medical/build/1.0.12/job/sr8nrcrybw7e47d5

This is not super high priority, but it would be good to investigate it at some point. I wonder if it could potentially be a pip bug.

**Comment by bsipocz** [comment]
Switch to travis+windows to get this functionality.
