### ISSUE TITLE
Circle ci support

### ISSUE THREAD

**Issue by goanpeca** [astropy/ci-helpers#112]
First of all thanks for the work on this.

I managed to (in a kinda hacky way) use the ci-helpers within circle ci for different versions of python (up to 4 different, and one per container)

Since every command in circle ci is its own shell, the path needs to be updated on every command (a bit annoying...!).

Also I had to use Travis names for the env variables which is fine, but we could perhaps expand on something like this¿
https://github.com/spyder-ide/qtpy/blob/master/circle.yml

Cheers

**Comment by astrofrog** [comment]
Supporting Circle CI would be great!

**Comment by goanpeca** [comment]
Ok cool, hmm first step would be a more complex use case?

A test example for the astropy case maybe?

**Comment by goanpeca** [comment]
@astrofrog just wondering, if you have given more consideration to CIRCLE-CI working with ci-helpers.

Any chance of providing more test environments in order to support sequential builds on circle ci?
Or provide an argument to the bash scripts that corresponds to the test environment name?

source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh "test_qt4" 
source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh "test_qt5"

Something like that would really make life easy for projects that need a big matrix and want to break CI services inlcuding circle ci, which only provides 4 containers.

**Comment by goanpeca** [comment]
Things that would be needed:
1. `setup_conda.sh` script needs to understand that it is running on circle CI and act accordingly, so circle-ci support could assume a linux machine.
2. What I use here as  `PY_VERSIONS: "2.7 3.4 3.5"`, could become a dependencies per circle-ci node, so something like

CONDA_DEPENDENCIES: "pyqt pytest pytest-cov"
CONDA_DEPENDENCIES_0: "python=2.*"
CONDA_DEPENDENCIES_1: "python=3.5"

**Comment by larsoner** [comment]
FYI the way we have gotten CircleCI to work without needing to constantly append paths is by:

1. adding the PATH [at the top](https://github.com/mne-tools/mne-python/blob/master/circle.yml#L4)
2. [removing the default env](https://github.com/mne-tools/mne-python/blob/master/circle.yml#L38)

From there things are much less painful. Maybe this could be the suggested path, then CircleCI support probably isn't so bad, and using CI-Helpers might be easy enough.
