### ISSUE TITLE
Suggestion: quickly fail appveyor builds if a new commit is pushed to a PR

### ISSUE THREAD

**Issue by mwcraig** [astropy/ci-helpers#115]
The conda-forge people use the bit of code below to cancel an appveyor build of a PR if there is a newer commit in the PR when the appveyor build starts. We haven't been really backed up since 1.2 came up but it might be helpful in the future: https://github.com/conda-forge/staged-recipes/blob/master/appveyor.yml#L56-L64

**Comment by astrofrog** [comment]
+1 - can we do something like this for Travis too?

**Comment by bsipocz** [comment]
+1 - I wonder whether we can do it here in ci-helpers, or this should always go into ``appveyor.yml``?

**Comment by bsipocz** [comment]
Btw dows it pick it up if it's not on a new commit on a PR, but on master?

**Comment by mwcraig** [comment]
It looks specifically for pull requests, I think.

**Comment by mwcraig** [comment]
Rolling builds, which fail immediately when a new commit is made to the same branch or pull request, can be enabled in the appveyor settings. Just turned it on on the conda-channel-astropy, though now that I think about it, that may have been a mistake.

**Comment by eteq** [comment]
Hmm, just noticed on the [jobs part of the travis API docs](https://docs.travis-ci.com/api#jobs): "CANCEL JOB".  So looks like it's possible, but it might be more trouble than it's worth given the authorization requirements?

**Comment by bsipocz** [comment]
Closing as this can be configured on the repos' travis page for a few weeks now, and is something that should be set on the repo rather on the PR level.
