### ISSUE TITLE
Remove default channels (astropy, openastronomy, astropy-ci-extras)

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#119]
At the moment four channels are used unless the user sets ``CONDA_CHANNELS``. These are ``defaults``, ``astropy-ci-extras``, ``astropy``, and ``openastronomy``.

Recently we saw a few problems when a package is available in both ``astropy`` and ``openastronomy`` and still somehow the build ends in conflicts, e.g. https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/147998479#L526

So I propose to remove openastronomy from the default channels (as we tend to host all of dependencies of the affiliates in astropy). Should any package needs something from that channel they can specify it in  ``CONDA_CHANNELS``.

Thoughs @astrofrog, @mwcraig?

**Comment by mwcraig** [comment]
I would maybe remove astropy instead but definitely remove once of them.

**Comment by bsipocz** [comment]
Yes, that's indeed more logical, but before doing it the package copying over from astropy to openastronomy needs to be automated first, and should include the dependencies of affiliated.

**Comment by astrofrog** [comment]
Actually I would like to suggest we remove all channels, and instead have packages explicitly opt in to the ones they need. This is I think important now that ci-helpers is used by non-astro packages.

**Comment by bsipocz** [comment]
@astrofrog - That would be indeed a logical step. 

However I think we should then first open PRs for most of our affiliated packages to  add the channels to prevent an avalanche of questions due to the suddenly failing travises.

**Comment by astrofrog** [comment]
@bsipocz - I agree :)
