### ISSUE TITLE
Does coverage still need to be pinned to 3.7.1?

### ISSUE THREAD

**Issue by weaverba137** [astropy/ci-helpers#133]
I'd like to be able to use ci-helpers run coverage tests under Python 3.5, but coverage 3.7.1 doesn't appear to work.  Is there a reason that it is still pinned to 3.7.1 by default?

**Comment by eteq** [comment]
Looks like #132 has some discussion on this...?

**Comment by bsipocz** [comment]
Closing this as #132 has been just merged.
