### ISSUE TITLE
Appveyor fail?

### ISSUE THREAD

**Issue by goanpeca** [astropy/ci-helpers#137]
Just ran into this issue

```
git clone git://github.com/astropy/ci-helpers.git
Cloning into 'ci-helpers'...
powershell ci-helpers/appveyor/install-miniconda.ps1
Installing miniconda latest for -x64 bit architecture to C:\conda
Downloading Miniconda-latest-Windows-x86_64.exe from https://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
Exception calling "DownloadFile" with "2" argument(s): "The request was 
aborted: Could not create SSL/TLS secure channel."
At C:\projects\qtawesome\ci-helpers\appveyor\install-miniconda.ps1:45 char:8
+        $webclient.DownloadFile($url, $filepath)
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Installing C:\projects\qtawesome\Miniconda-latest-Windows-x86_64.exe to C:\conda
C:\projects\qtawesome\Miniconda-latest-Windows-x86_64.exe /InstallationType=AllUsers /S /AddToPath=1 /RegisterPython=1 /D=C:\conda
Start-Process : This command cannot be run due to the error: The system cannot 
find the file specified.
At C:\projects\qtawesome\ci-helpers\appveyor\install-miniconda.ps1:65 char:5
+     Start-Process -FilePath $filepath -ArgumentList $args -Wait -Pass ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp 
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C 
   ommands.StartProcessCommand
 
Failed to install Python in C:\conda
Command exited with code 1

```

Is this an appveyor thing?

**Comment by astrofrog** [comment]
Looks like this error is mentioned in here: https://www.appveyor.com/docs/how-to/download-file/ - we're seeing this on Astropy too now. I'm going to try the workaround suggested.

**Comment by astrofrog** [comment]
@goanpeca - I'm not sure what changed in the last day (whether on the AppVeyor or Continuum servers) but #138 fixes this. I'll merge it once all the tests pass, which could be another hour or so. On the plus side, the nice thing about ci-helpers is we only need to fix it in one place!

**Comment by goanpeca** [comment]
@astrofrog I believe that we changed yesterday to a new CDN provider, could that have caused this?

**Comment by astrofrog** [comment]
@goanpeca yes, that seems likely. I'm not familiar enough with SSL to understand whether this is a mis-configuration of the CDN or whether it is due to the CI environments not supporting recent enough SSL protocols. I'm not sure what the best workaround is at this point - do you have any suggestions?

**Comment by goanpeca** [comment]
@kalefranz

**Comment by astrofrog** [comment]
Just for info, we're working around this for now by simply using http instead of https, but it would be nice to have a longer term fix.

**Comment by astrofrog** [comment]
(just to be clear, the temporary fix is merged now so you can restart any build - without having to rebase/force push)

**Comment by kalefranz** [comment]
https://www.appveyor.com/docs/how-to/download-file/#start-filedownload-cmdlet

> If you are getting the following error while downloading
> 
>     Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
>     Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.
>
> this most probably means that build worker and server could not agree on SSL protocol, because server does not support modern protocol with highest security. If you understand this security risk and trust that server, you can relax SSL client settings in build PowerShell session by the following statement called before Start-FileDownload
> 
>     [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'

Does this imply the default is to only accept TLS 1.3?  That seems odd.  TLS 1.3 is still just a draft.

**Comment by astrofrog** [comment]
@kalefranz - this was also failing on Travis though, so it's not just an AppVeyor issue.

**Comment by kalefranz** [comment]
@astrofrog Can you give me a link to the Travis failure?

**Comment by kalefranz** [comment]
FYI: https://www.ssllabs.com/ssltest/analyze.html?d=repo.continuum.io&s=104.16.18.10&hideResults=on&latest

**Comment by kalefranz** [comment]
Can someone try again?  I've actually relaxed the TLS settings.  They may have been too strict before.

**Comment by astrofrog** [comment]
@kalefranz - I'm trying again here: https://github.com/astropy/ci-helpers/pull/139

**Comment by astrofrog** [comment]
It worked - thanks @kalefranz!

**Comment by goanpeca** [comment]
woot :-)
