### ISSUE TITLE
NUMPY_VERSION=prerelease Travis test errors out.

### ISSUE THREAD

**Issue by weaverba137** [astropy/ci-helpers#152]
I needed to run a test against Numpy 1.12.0rc2.  I tried running a Travis test with `NUMPY_VERSION=prerelease`, but the test exited prematurely (resulting in a Travis error rather than a failure).  When I ran the test by hand, I found that the prerelease version was trying to load MKL libraries and failing.  When I look at the setup_dependencies_common.sh file, I can see that nomkl is preinstalled for NUMPY_VERSION=dev* but not NUMPY_VERSION=pre*.

If this is intentional, how can I work around this problem?

**Comment by weaverba137** [comment]
Adding 'nomkl' to CONDA_DEPENDENCIES appears to be a successful workaround, but this should probably be documented at the least.

**Comment by bsipocz** [comment]
@weaverba137 - Could you please post a link for the failing travis? I don't see this problem with any of the other repos testing against the prerelease (e.g https://travis-ci.org/astropy/astropy/jobs/191953599#L529), and indeed numpy provides wheels for it's prereleases thus in theory it shouldn't behave differently than a released stable version.

**Comment by weaverba137** [comment]
Here's a test that failed: https://travis-ci.org/weaverba137/pydl/jobs/190443590

Note that there is not explicit error message; the test just crashes hard, resulting in a Travis error, not a failure.  I had to run the test by hand to get a proper error message.

And here's one that succeeded after the nomkl workaround: https://travis-ci.org/weaverba137/pydl/jobs/190456331

**Comment by astrofrog** [comment]
I think it makes sense to use ``nomkl`` when compiling Numpy from source. Maybe we just need to make that a standard part of the ci-helpers script.

**Comment by bsipocz** [comment]
@weaverba137  - This is a weird one, and I remember seeing this with other packages and numpy prerelease, but we usually ignored it being a timed out test nothing more. Thanks for reporting and digging into it.

@astrofrog  - As https://travis-ci.org/weaverba137/pydl/jobs/190443590#L561 shows it actually doesn't compile numpy but uses the wheel from pypi, however mkl was installed with numpy stable previously but hasn't been removed. Do you think it's better to try to hack and stop mkl being installed at the first place, or remove it by hand before installing the prerelease with pip?

**Comment by astrofrog** [comment]
I think it would make sense to install nomkl if we know that we're going to install Astropy from pip eventually. There may be other packages that rely on MKL (e.g. scipy?) that would have issues if we force remove mkl.
