### ISSUE TITLE
CONDA_CHANNELS separator

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#161]
I've run into an annoying issue yesterday in #160 namely that our a space separated ``CONDA_CHANNELS`` variable is also a conda variable, though they prefer it to be coma separated and thus it makes the install end up in an ugly fail.

It looks like that the ``Miniconda-*`` scripts don't recognize this variable, while ``Miniconda2-*`` and ``Miniconda3-*`` do. 

Hopefully there is a way to set the separator within our scripts. If there isn't, then we can use an older version of the windows version of Miniconda to fix #160.
Alternatively we update Miniconda to be Miniconda3-latest for all the platforms, change the API and require ``CONDA_CHANNELS`` to be coma separated, and open mass PRs to projects that use ``ci-helpers`` and use a space separated string.

Which way do you prefer @astrofrog?

https://github.com/conda/conda/issues/4579

**Comment by Cadair** [comment]
could you also write some bash wizardry that replaces space with comma in the env var before running miniconda? Horrible I know, but saves opening a lot of PRs.

**Comment by bsipocz** [comment]
Yes, I've thought about that. It's a good workaround for now but I feel it's a fundamentally bad approach, semi hiding the fact that a variable is not behaving as it should.

**Comment by Cadair** [comment]
indeed, at least doing that would provide backwards compatibility for a while (as it would not break if there were commas).

**Comment by bsipocz** [comment]
I'm on it, I love the hacking in bash, brings back memories from my youth ;)

**Comment by Cadair** [comment]
I do not share that love, hacking in bash brings me out in a rash :p (xonsh for ever!)

**Comment by bsipocz** [comment]
Oh, the bash part is joy, but the PS hurts like hell...

**Comment by bsipocz** [comment]
Fixed by #162.
