### ISSUE TITLE
Skip installing conda when building eggs and system python is available

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#163]
We should skip installing conda/python when language is set to python in travis, and are building eggs. This would save ~1min/job.

**Comment by pllim** [comment]
If language is set to C, can we still somehow respect the python setting (https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions)? Would make testing Astropy with Python 3.7 less hacky. :thinking:

**Comment by bsipocz** [comment]
If you set the language back to python, then yes. Also, I planned to change the language from C back to python (as I suspect the install will be a bit quicker, etc) just hasn't got there yet.
