### ISSUE TITLE
Make Appveyor more flexible for NUMPY_VERSION

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#17]
At the moment it needs to be set to a version, and ``dev`` or ``development`` or ``stable`` is not supported.

**Comment by astrofrog** [comment]
I've added support for ``stable`` in #21

**Comment by astrofrog** [comment]
(and I'm trying ``dev`` too)

**Comment by bsipocz** [comment]
:+1:

**Comment by astrofrog** [comment]
Numpy dev will require https://github.com/numpy/numpy/issues/6701 to be fixed

**Comment by astrofrog** [comment]
https://github.com/astropy/ci-helpers/pull/21 includes a Numpy dev build that is marked as an allowed failure. Once we get the build to work, we can remove the allowed failure part.

**Comment by astrofrog** [comment]
Done in #21 and #22 :)
