### ISSUE TITLE
Problems using ci-helpers on non astropy related projects.

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#180]
I've tried to use your CI-helper scripts for another project that isn't related to astropy at all. For some reason as soon as I use these scripts to install dependencies the travis build fails. Even though the log says that everything went OK.

[Travis Build](https://travis-ci.org/MDAnalysis/mdanalysis/builds/218435158)

[Commit](https://github.com/MDAnalysis/mdanalysis/commit/653263c89fddf4128fed7104540d5eae633526ef)

You can also close this issue if you like since the project isn't related to astropy.

**Comment by bsipocz** [comment]
@kain88-de - No worries, many non astropy related project uses this. I'll try to have a look at the logs.

**Comment by bsipocz** [comment]
There is one obvious mistake, it may be be the culprit.
E.g. this https://travis-ci.org/MDAnalysis/mdanalysis/jobs/218435160#L296 doesn't look good.

Could you use ``DEBUG=True``? that would give a more verbose install log.

**Comment by kain88-de** [comment]
Thanks for the help. 

[Whole Travis Build](https://travis-ci.org/MDAnalysis/mdanalysis/builds/218623024)

There is one very [peculiar job](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/218623027) though. Our linter seems to finish fine according to the logs. But the job still fails

**Comment by kain88-de** [comment]
Here is a link to the PR with all commits.

https://github.com/MDAnalysis/mdanalysis/pull/1282

**Comment by bsipocz** [comment]
@kain88-de - I have no idea why it fails. E.g. it seems that the tests return the same result as in previous runs and the after success part of the script is running, too.

https://travis-ci.org/bsipocz/mdanalysis/jobs/218965402#L1831
