### ISSUE TITLE
backport packages aren't installable via conda

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#181]
[Travis log](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/218623027#L496)

The script has problems with packages that contains a dot symbol. Like the `backports.*` packages. The dependency gets installed via pip during the CI step.

**Comment by kain88-de** [comment]
I assume the dot in the package name somehow breaks your code to determine the version string

https://travis-ci.org/MDAnalysis/mdanalysis/jobs/219177564#L466

**Comment by bsipocz** [comment]
Indeed this seems to be a bug, though it's nicely worked around with falling back to pip install.
