### ISSUE TITLE
Sudden failure of CRON jobs

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#187]
At MDAnalysis we notice for a few days that pure cron jobs fail. [Travis Log](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/229066342)
There hasn't been a change in our configuration since this is happening but travis updated one of their images [blog entry](https://blog.travis-ci.com/2017-05-04-precise-image-updates).

I'm not sure what the issue is but the normal `exit` to abort cron jobs for a seems to cause the failure now.

PR for this at MDAnalysis: https://github.com/MDAnalysis/mdanalysis/pull/1334

**Comment by bsipocz** [comment]
There is something weird here, as the cron only jobs are still exited properly yesterday for astropy. How long do you see this issue?

**Comment by bsipocz** [comment]
I don't see much that we could do here, I suggest to raise this issue at travis maybe the will have better insight.

**Comment by kain88-de** [comment]
for about 3-5 days now. I've already written to the travis support today and I'm waiting for an answer.

**Comment by joepvd** [comment]
Could you try to use the function `travis_terminate 0` instead of `exit 0`?

An alternative would be to call `set +e` right before `exit 0`.

See https://github.com/travis-ci/travis-build/pull/1047/commits/66bd59b851ac925df31caeca33d7883b953e6b32 for more information.

**Comment by bsipocz** [comment]
PR is opened in #189. I'm not sure how we run the tests for it here, as never saw the failure either here or in any other astropy related project. Anyway, once it's merged I'll ping you @kain88-de to try it out.

**Comment by kain88-de** [comment]
@bsipocz I'll try it from my repository first OK. Then we can savely test the fix

**Comment by kain88-de** [comment]
@bsipocz [works](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/232501355)

**Comment by bsipocz** [comment]
@kain88-de - Thanks.
