### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#197]
I'm seeing the following error in the log on Windows:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda 4.1.11* -> conda-env >=2.5,<2.6 -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

Full log: https://ci.appveyor.com/project/glue-viz/glue-vispy-viewers/build/1.0.367

**Comment by bsipocz** [comment]
@astrofrog - is there a reason to use such an old conda version? We normally use 4.3.6 (but it's probably time to check whether never versions work fine).

**Comment by astrofrog** [comment]
Oh sorry I just saw it's because I had the conda version hard-coded. Oops!

**Comment by bsipocz** [comment]
On the other hand I don't really understand why that build went ahead and worked...

**Comment by astrofrog** [comment]
I'm very confused by that too! Maybe powershell doesn't stop if it encounters an error?

**Comment by bsipocz** [comment]
It should though, at least I remember to have fixed it for https://github.com/astropy/ci-helpers/issues/87. Maybe it's still not working properly...

**Comment by bsipocz** [comment]
Ah, ok now I see. #170 missed this install, just applied it for the later conda install steps.
