### ISSUE TITLE
Astropy LTS

### ISSUE THREAD

**Issue by cmccully** [astropy/ci-helpers#200]
I am having trouble getting my continuous integration to work on 
https://github.com/LCOGT/banzai/pull/94
The only issue is on the astropy LTS version (for both python 3 and 2.7). I have updated the astropy helpers to the newest version and the package template to the newest version.
When I run the build I get the error:
The 'test' command requires the astropy package to be installed and importable.
Above in the logs, it appears that astropy installs successfully and in fact, pip correctly finds and installed version of astropy. Any suggestions would be helpful.

**Comment by bsipocz** [comment]
Could you post a full traceback? I don't think it's a ci-helpers issue though, if you get the LTS installed as requested not much we can do about it here. 

However many changes were made since 1.0.x in astropy, so it's easily possible that your package is not compatible any more.

**Comment by cmccully** [comment]
Sorry. The link for the build is here:
https://travis-ci.org/LCOGT/banzai/jobs/241315690
The salient part of the error is here:
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py:331: UserWarning: Normalizing '0.7.9dev446' to '0.7.9.dev446'
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: The 'test' command requires the astropy package to be installed and importable.

Under the command: source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh 
(which is why I posted to ci helpers). The odd thing is that astropy appears to be installed:

The following NEW packages will be INSTALLED:
    mkl:   2017.0.1-0   
    numpy: 1.12.1-py27_0
Fetching package metadata .............
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda/envs/test:
The following NEW packages will be INSTALLED:
    astropy: 1.0.13-np112py27_0 astropy-ci-extras
Fetching package metadata .............

**Comment by cmccully** [comment]
Could you point me to the anaconda channel where the ci-helpers is getting the astropy LTS so I can see if I can reproduce the issue on my local machine? I wasn't able to access the ci-helpers anaconda channel.

**Comment by bsipocz** [comment]
@cmccully - the LTS release (when it's such old as the current on) comes from the ``astropy-ci-extras`` channel. Normally I would definitely try to sort this out, but now I'm rather short on time as we're very close to feature freeze for astropy v2.0.

**Comment by cmccully** [comment]
Ah. Ok. I didn't realize that v2.0 is so close. Is the astropy-ci-helpers channel open? It appears that I have to log in?
"You're trying to access a page that requires authentication."

**Comment by bsipocz** [comment]
It's ``astropy-ci-extras`` not ``astropy-ci-helpers``. Should be open: https://anaconda.org/astropy-ci-extras

**Comment by cmccully** [comment]
Oops. Sorry about that. I misread.
