### ISSUE TITLE
Add option to test 32 bit builds

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#201]
We have now an issue that our package doesn't pass the tests on 32 bit platforms. We haven't noticed so far but this is still an issue for people who want to package a python package since most distributions haven't dropped 32 bit support yet. The solution would be to download the 32bit version of conda.  See [obspy](https://github.com/obspy/obspy/pull/1580) for how to do it.

**Comment by astrofrog** [comment]
@kain88-de - we do 32-bit testing for Astropy via CircleCI. We have a docker image for that. We could probably document this here or at least point to it.

**Comment by bsipocz** [comment]
If there is anyone volunteering to do it we could probably add some kind of CircleCI support here. I believe there is already an issue for it (#112)

**Comment by kain88-de** [comment]
@jbarnoud is currently testing a travis version. (https://github.com/MDAnalysis/mdanalysis/pull/1392)

**Comment by kain88-de** [comment]
There is also a longer discussion of adding unix 32bit support for conda-forge https://github.com/conda-forge/conda-forge.github.io/issues/163

**Comment by jbarnoud** [comment]
I am working on it in this branch: https://github.com/jbarnoud/ci-helpers/tree/32bits
I'll make a pull request if it ends up working, but so far I have some trouble compiling C extensions for 32 bits python on 64 bits travis.
