### ISSUE TITLE
Preferred way to set pytest version

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#210]
I've seen in the script that ci-helpers installs an older version of pytest for compatibility reasons. But we would like to use a newer version of pytest. What is the recommended way to install the most recent version? I've seen a `PYTEST_VERSION` variable is checked during the installation but I don't understand how it would make a difference in the installation since the astropy-ci-extra repository only has version 2.7.3.  Our current solution is to add pytest with a specific version to the CONDA_DEPENDENCIES variable.

**Comment by bsipocz** [comment]
@kain88-de - Could you link a build where you got an old version installed? The install should pick up the latest version if ``PYTEST_VERSION`` wasn't set to something else.

We have the old version in the astropy-ci-extras channel to support the need of the old LTS astropy version, but that shouldn't be picked up for packages that doesn't require an old pytest.

**Comment by kain88-de** [comment]
Here is a build [travis](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/245336252). The log states that only pytest 2.7.3 is installed.  In this build I don't set pytest as a conda dependency.

I see from the astropy master branch builds that you indeed install the newest pytest there. But I can't find in the `setup_dependencies_common.sh` file where it would installed the newest version. There is only one [line](https://github.com/astropy/ci-helpers/blob/df405d059931af755a42e88526e9cf3e64416590/travis/setup_dependencies_common.sh#L98) installing it from the astropy-ci-helpers repository.

Excuse the messy settings of environment variables. We are just transitioning from nose to pytest. This is also not super urgent. We will clean up the travis.yml file after the transition is complete.

**Comment by bsipocz** [comment]
@kain88-de - This is very weird indeed. Could you add a ``DEBUG=True`` to that build? That line you're citing should search for suitable packages to install from the channels you've listed in ``CONDA_CHANNELS`` and also astropy-ci-extras channel, and pytest-3.1.2 is available both on defaults and conda-forge.

**Comment by kain88-de** [comment]
OK it's news to me that `conda install -c channel package` looks for the most recent version in any available channel. I thought it would only look in the specified channel. But I think I now know the problem. We set `$CONDA_CHANNEL_PRIORITY=True`, this might actually cause only the astropy-ci-extra repository to be considered when pytest is installed like this.  

I will start a build removing the channel priority to test/confirm my theory.

**Comment by bsipocz** [comment]
@kain88-de - Oh, yes, that will be it. If you set it to true, I believe the latest channel added will take priority.

**Comment by kain88-de** [comment]
Yes removing the channel priority fixed the version issue 

https://travis-ci.org/MDAnalysis/mdanalysis/jobs/245372469

**Comment by bsipocz** [comment]
Thanks. I'm interested in what you plan to come up with as the only way I see is to override channel_priority to be false for that single install command.

**Comment by kain88-de** [comment]
I will add your repository to condarc as the channel with the lowest priority. Then we don't need to specify the channel when installing pytest. Version pinning of pytest should still work. This will be ok as long as all packages in the astropy repository are outdated and newer versions exist in defaults.

**Comment by bsipocz** [comment]
That approach won't work, we definitely don't want to add channels to the rc file that packages didn't asked for. (Been down that path at the beginning of this project and it lead to more issues than solved).

**Comment by kain88-de** [comment]
It would work if you use channel priority by default. Another solution is to check the pinning version of pytest and add the channel if that value is 2.7.3

**Comment by bsipocz** [comment]
Most of the packages doesn't use channel priority (we had quite serious issues with it in the past, thus was the option of opting out added to conda). I'll go ahead an add the workaround I've proposed above and it still seems to be the cleanest and simplest and most generic one.

**Comment by kain88-de** [comment]
Yeah I don't see much alternative solutions either.

**Comment by kain88-de** [comment]
Thanks
