### ISSUE TITLE
pytest-xdist has no `--parallel` option

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#213]
pytest-xdist doesn't have a parallel option argument. It has a `numprocesses` argument though in the current version.  I'm not sure if `parallel` is used somewhere in the astropy ecosystem but I would suggest adding `numprocesses` to the list of recognized options that will install pytest-xdist.

Here is the full help for xdist.

```bash
distributed and subprocess testing:
  --boxed               box each test run in a separate process (unix)
  -f, --looponfail      run tests in subprocess, wait for modified files and
                        re-run failing test set until all pass.
  -n numprocesses       shortcut for '--dist=load --tx=NUM*popen', you can use
                        'auto' here for auto detection CPUs number on host
                        system
  --max-slave-restart=MAX_SLAVE_RESTART
                        maximum number of slaves that can be restarted when
                        crashed (set to zero to disable this feature)
  --dist=distmode       set mode for distributing tests to exec environments.
                        each: send each test to each available environment.
                        load: send each test to available environment.
                        (default) no: run tests inprocess, don't distribute.
  --tx=xspec            add a test execution environment. some examples: --tx
                        popen//python=python2.5 --tx socket=192.168.1.102:8888
                        --tx ssh=user@codespeak.net//chdir=testcache
  -d                    load-balance tests. shortcut for '--dist=load'
  --rsyncdir=DIR        add directory for rsyncing to remote tx nodes.
  --rsyncignore=GLOB    add expression for ignores when rsyncing to remote tx
                        nodes.
```

**Comment by bsipocz** [comment]
``--parallel`` is used in the astropy testing framework: http://docs.astropy.org/en/stable/development/testguide.html#astropy.test

The issue with ``numprocesses`` is that ``-n`` seems rather ambiguous, I can easily imagine a ``SETUP_CMD`` has a command that is not pytest and thus ``-n`` is used for something else.

**Comment by kain88-de** [comment]
yeah the `-n` is ambiguous, Sorry I read the help test yesterday that `--numprocesses` would also be a viable option to select the number of subprocesses.

**Comment by bsipocz** [comment]
@kain88-de - That would be nice, maybe you can suggest it in the ``pytest-xdist`` repo?

**Comment by kain88-de** [comment]
Looks like this option name will be in the next version of pytest-xdist.
