### ISSUE TITLE
Question: does '--open-files' use a astropy test helper?

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#215]
I see that you support an `--open-files` option for the tests to install psutil. Is this something specific to astropy? I'm interested because I would like to port a noseplugin to check for open-files in tests to pytest.

**Comment by astrofrog** [comment]
@kain88-de - yes, you can most clearly see the code separated out into its own file in this pull request:

https://github.com/astropy/astropy/pull/5770

**Comment by kain88-de** [comment]
Thanks for the answer
