### ISSUE TITLE
Pip install fallback uses wrong syntax for version matching

### ISSUE THREAD

**Issue by drdavella** [astropy/ci-helpers#228]
I'm not sure whether or not this is a duplicate of #194. I got the following error on an appveyor build: 

>Installing astropy with conda was unsuccessful, using pip instead
>Invalid requirement: 'astropy=1.3.2'
>= is not a valid operator. Did you mean == ?
>ERROR: the last command returned the following exit code: 1

I believe that `conda` understands both `=` and `==` for pinning a particular package version, so it should be enough just to update the following lines to use `astropy==` instead:
https://github.com/astropy/ci-helpers/blob/ba5628ab394c3afb2d89c31d496f3691b8202974/appveyor/install-miniconda.ps1#L191-L195

This also appears to affect the logic for `numpy` and `sunpy`.

**Comment by bsipocz** [comment]
#333 should fix this.
