### ISSUE TITLE
Recommend cloning with --depth=1?

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#229]
This may not be a bad idea:

https://github.com/Anaconda-Platform/anaconda-client/blob/develop/.travis.yml#L29

Should we recommend this?

**Comment by bsipocz** [comment]
Oh, sure it's very sensible idea.
 
Whenever we need to debug something from the packages point of view, we need to change the cloning anyway to point to a fork and feature branch.

**Comment by pllim** [comment]
Is this still relevant? With `setuptools_scm`, shallow clone won't work anymore?

**Comment by bsipocz** [comment]
We don't do versioning for ci-helpers, so I'm not sure how `setuptools_scm` changes things here?

**Comment by bsipocz** [comment]
However #235 did just what was suggested, so closing this sounds reasonable (I don't think it's worth much of our time to batchPR the shallow clones downstream).

**Comment by pllim** [comment]
Ah, sorry, I misunderstood the issue. Sorry for the noise!

**Comment by pllim** [comment]
p.s. I agree batchpr is not necessary, as this repo is not very big anyway.
