### ISSUE TITLE
Add banner to log with information on ci-helpers

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#231]
When ci-helpers is run, it might be helpful to have a custom banner shown with e.g. information on reporting issues, but also could include information about things that we change that could potentially break builds, so that people looking through problematic logs would see this. The banner could be stored in a file and shown on both Travis and AppVeyor.

**Comment by bsipocz** [comment]
I don't yet know anything about how to add these banners to travis or appveyor. But very keen to have a quick sprint on it at CC mtg if we have time.

**Comment by astrofrog** [comment]
I meant something a lot simpler - just having a section in the log which gives some standard text :)

**Comment by bsipocz** [comment]
Oh, OK, that's actually something easily implementable.
