### ISSUE TITLE
ENH: Add support for `environment.yml` files

### ISSUE THREAD

**Issue by larsoner** [astropy/ci-helpers#232]
Over at MNE we want to ship a Conda `environment.yml` to help people get up and running, and it would be great if we could test it with Travis. If people think it's worthwhile to add support for this to CI-helpers, I'm happy to give it a shot. Maybe a `CONDA_ENVIRONMENT` env var that, when found, just uses the given `yml` file ~~and ignores~~ EDIT: *in addition to* using the standard `CONDA_DEPENDENCIES` and `PIP_DEPENDENCIES`?

**Comment by astrofrog** [comment]
That seems reasonable - @bsipocz, do you agree?

**Comment by bsipocz** [comment]
Sounds good to me, too.
