### ISSUE TITLE
Test skipping astropy=lts

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#238]
For example https://travis-ci.org/ejeschke/ginga/jobs/280592621

`The latest stable version of astropy is an LTS version, skipping testing as LTS`

Is this expected behavior?

**Comment by bsipocz** [comment]
Yes, no need to test against both stable and lts when they are the same. ci-helpers will recognize when 3.0 is out, it's not the same as lts.

**Comment by pllim** [comment]
Ah, okay. Thanks!
