### ISSUE TITLE
Test using numpy=prerelease has funky log message (need better message when prerelease is not available)

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#239]
Example from astropy core:
https://travis-ci.org/astropy/astropy/jobs/280665134

Example from Ginga:
https://travis-ci.org/ejeschke/ginga/jobs/280675375

Both stopped at this message:
```
Package plan for installation in environment /home/travis/miniconda/envs/test:
The following NEW packages will be INSTALLED:
    libgfortran: 3.0.0-1            
    nomkl:       1.0-0              
    numpy:       1.13.1-py36_nomkl_0 [nomkl]
    openblas:    0.2.19-0           
DEPRECATION: The default format will switch to columns in the future.
You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf
under the [list] section) to disable this warning.
```

But Travis CI reported green status. What does this mean?

**Comment by bsipocz** [comment]
This is a pip warning on the command line, but I haven't looked into the details yet (saw it locally, too). 

The travis CI will always report green when there is no prerelease available as it doesn't run the tests in that case. It's a bit misleading, but we thought it's better than running the tests with stable and report back on that. Please open a PR for the README if you have ideas how to explain it better.

**Comment by pllim** [comment]
Oh... yeah. I remember now I was confused by this same thing some time ago too. 😅

**Comment by pllim** [comment]
How about doing an `echo "No prerelease available, stopping test"` right before `travis_terminate 0` when no prerelease is found? Will that work?

**Comment by bsipocz** [comment]
Oh sure, that would work. Will you open a PR, or should I mix it into another?

**Comment by pllim** [comment]
Adding an `echo` is easy enough but I am not sure how to test it.

**Comment by bsipocz** [comment]
We don't ;) I was just asking as waiting for the ci here is a nightmare, so adding it into something that also does a fix may make some sense. In case you want to hack on ci-helpers ;)

**Comment by pllim** [comment]
I am focusing on the bot (and my day job) right now, so unlikely to hack here in short term, so feel free to add the `echo` as part of another PR. Thanks!

**Comment by pllim** [comment]
Thanks @bsipocz !
