### ISSUE TITLE
Pip fallback should specify --no-deps

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#241]
In this build, Numpy got upgraded by the pip fallback:

https://travis-ci.org/cdeil/healpix/jobs/281350465

**Comment by bsipocz** [comment]
Oops, thanks.

The other issue with the fallback though, that people will need to make sure they list all dependencies in the list, as pip would not even have pick up everything conda does. And if we add no-deps, it will pick up even less.

**Comment by bsipocz** [comment]
Do you think we should indeed use ``--no-deps``, or would ``--upgrade-strategy only-if-needed`` would be sufficient, too? (Sadly I didn't find an option for install dependencies, but don't update already installed ones, maybe that's a feature request to pip)

**Comment by bsipocz** [comment]
Here is a feature request for pip to add the "never" option to ``--upgrade-strategy``: https://github.com/pypa/pip/issues/4745
I think that would perfectly match out needs, otherwise it will be a really ugly hack to make pip understand and honour the versions in the conda pinned file.
