### ISSUE TITLE
[docs only] with pycodestyle

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ci-helpers#245]
Would it make sense to run the PEP8 tests even if a commit is labelled `[docs only]`? For example trailing whitespaces are a common "problem" even if it's just about docstrings - and the pycodestyle test doesn't take long (at least compared to the 1 minute each tests requires to realize it doesn't need to run because of `[docs only]`).

**Comment by bsipocz** [comment]
Sure, that sounds perfectly sensible to me. Are you interested in doing a PR, or shall I? 
(Note that master is super protected here, so any PRs needs to be rebased every time another PR gets merged).

**Comment by MSeifert04** [comment]
It would probably be non-trivial for me, so if you have the time I would prefer if you did the PR. :)

**Comment by bsipocz** [comment]
Sure.
