### ISSUE TITLE
Show commands executed in setup scripts

### ISSUE THREAD

**Issue by cdeil** [astropy/ci-helpers#25]
Is it possible to change the setup so that the executed commands appear in the travis-ci log?

Currently only
```
$ source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
```
is displayed and then the output from the commands in that script, but not the commands themselves.
Example: https://travis-ci.org/astropy/ci-helpers/jobs/92443363#L268

This makes the logs very hard to read and makes it  difficult to debug issues if one of those commands fails or doesn't do what one expects. It's cost me a few hours over the past year and it's always frustrating when issues happen at that stage.

On the other hand, the travis-ci part of the build log is usually very easy to read because the commands are printed and even highlighted / grouped in the build log.

I'm not familiar much with shell scripting, but there should be a flag / option to run these scripts so that commands are echoed before they are executed, no?

**Comment by astrofrog** [comment]
Yes, we can add ``/bin/bash -x`` at the top of the helpers set-up scripts.

**Comment by bsipocz** [comment]
actually ``#!/bin/bash -x`` is already there at the top, but  it seems to be ignored by source, so I would vote to use ``set -x`` and ``set +x`` in the script itself.

**Comment by cdeil** [comment]
FYI: I Googled around a bit and tried things like `set -x` and `set +x` (not sure what exactly) in the past and didn't get this to work. I hope you can figure it out somehow...

**Comment by bsipocz** [comment]
@cdeil - Would something like this be helpful? 
https://travis-ci.org/bsipocz/ci-helpers/jobs/93799028#L289

It only has the ``set -x``, so more noise is generated at the end of the log, we should definitely turn this off before the script goes back to the travis.yml part.

**Comment by cdeil** [comment]
It's still hard to read, but I think all the info is there, so it's better, no?

Would it be helpful to very clearly echo something very visible to show where the script starts / ends?
Something like
```
===== start executing script.sh =======
```
and then
```
====== continue executing .travis.yml ======
```

I'm not sure ... put what you think is best to read / browse the log.

I saw 
```
set -ex
```
in https://github.com/numpy/numpy/blob/master/tools/travis-test.sh#L2

I think that means exit the script on first error.
Maybe that makes is simpler to see / notice issues from that part of the build?

**Comment by bsipocz** [comment]
Yes, we can add the ``-e`` option, too. Not sure about the extra prints, but if you find it useful we can have that, too.
Usually I use the little arrow like triangles, the script output is always within a dropdown, and it returns back to travis.yml right after that.

**Comment by bsipocz** [comment]
https://travis-ci.org/bsipocz/ci-helpers/jobs/93803080#L485
