### ISSUE TITLE
Install pytest-astropy for astropy=stable once v3.0 is out.

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#254]

**Comment by astrofrog** [comment]
Also for astropy=dev. Though is there any harm in installing it with older versions? Does it actually cause issues?

**Comment by bsipocz** [comment]
@astrofrog - It's already been installing for the dev version. I haven't added it for older version based on @drdavella's comment here: https://github.com/gammapy/gammapy/issues/1200#issuecomment-342850672

**Comment by drdavella** [comment]
@astrofrog, yes the plugins in `pytest-astropy` will conflict with the same plugins that were provided by older versions of `astropy`, and `pytest` will not be happy.

**Comment by bsipocz** [comment]
The pytest-astropy compatibility has now been solved for the 2.0.x branch, too, so I'm going ahead with this.
