### ISSUE TITLE
pytest-astropy broke tests using ci-helpers but not remote_data

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#255]
#253 caused an error like https://travis-ci.org/STScI-JWST/jwst/jobs/299741116 . In that case, the package uses `ci-helpers` but has no intention to use `@remote_data` feature.

c/c @stscieisenhamer @jaytmiller

**Comment by drdavella** [comment]
The real solution to this issue should be https://github.com/astropy/pytest-remotedata/issues/18.

**Comment by pllim** [comment]
Ah, okay. Feel free to close this if you don't want duplicate issues.

**Comment by drdavella** [comment]
I'm not sure it's technically a duplicate, but the fix here should not be necessary once the one in `pytest-remotedata` goes through.

**Comment by bsipocz** [comment]
Yes, I think @drdavella is right, this is an issue for `pytest-remotedata`. If ci-helpers doesn't install `pytest-astropy`, should do that  manually in the travis file of jwst as if you use the test runner of astropy, you'll need it.

Though if you don't use the test runner, but use astropy-dev, then we ought to have a workaround. But if the ETA of fixing it upstream is acceptable for you, that would be a nicer solution.

**Comment by pllim** [comment]
Upstream is fine. I think I found a workaround. But I wonder if other packages would run into the same problem.

**Comment by bsipocz** [comment]
I believe this is now fixed with pytest-astropy 0.2.1. Feel free to reopen otherwise.
