### ISSUE TITLE
docs only annotation doesn't seem to be working consistently

### ISSUE THREAD

**Issue by eteq** [astropy/ci-helpers#270]
The ``[docs only]`` seems to have failed in at least one case for no clear reason.   The last commit of astropy/astropy#7175 has ``[docs only]`` in the changelog entry, but if you look at https://travis-ci.org/astropy/astropy/builds/339514696 you'll see the full tests were running (although I canceled some of them when I noticed it).  

And they *are* definitely running, rather than the expected behavior of starting but then almost immediately passing (the normal ``[docs only]`` behavior) - some even ran to completion before I noticed it was happening.

**Comment by bsipocz** [comment]
@eteq - It seems that the error was in the commit message, as I used `docs_only` rather than `docs only`. Around the same time another `docs only` build behaved as expected https://travis-ci.org/astropy/astropy/builds/339537919.
