### ISSUE TITLE
Automatically determine latest stable versions

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#279]
To avoid having to always manually update the latest stable versions, I propose that we write a small script that takes the package name and Python version and returns the latest stable version of the package:

```
$ python get_latest_stable.py astropy 3.6
3.0
```

The pieces needed to construct this are as follows:

The JSON API for PyPI can be used to get an easily parseable list of releases:

https://pypi.python.org/pypi/astropy/json

The issue is that this doesn't include python-requires. However, the following URL provides a way to link package filenames with data-requires-python:

https://pypi.python.org/simple/astropy/

So I would suggest using this latter list to construct a dict of package filename to data-requires-python, then using the JSON API to cycle through the different versions backwards until one of them matches the Python version needed.

Ideally we should get PyPI to expose data-requires-python in the JSON API (https://github.com/pypa/warehouse/issues/3024), but in the mean time the above might not be too bad with requests and beautifulsoup.

We could still have a section in the CI setup that allows the version to be hard-coded and override this if needed, but the idea is that most of the time this wouldn't be needed.

Note that anaconda.org also has an API, so we could also do something similar with that if we didn't want to rely on pip versions but conda versions.

**Comment by kain88-de** [comment]
> Note that anaconda.org also has an API, so we could also do something similar with that if we didn't want to rely on pip versions but conda versions.

That might beneficial in cases where anaconda hasn't yet updated numpy (that takes less then a day usually but might fail some builds).

**Comment by bsipocz** [comment]
First of all we only need this feature for astropy and numpy. While it would be nice to avoid the need to update these manually, actually I'm not in favour of getting the version info from pypi. 
In reality none of the packages are in real rush to not being able to wait a few more days for the conda packaging, and the fallback to pip installing proved more problematic than useful.

So, it's OK if we can get this info from anaconda, but probably there are some other places to improve ci-helpers that have more impact.

(e.g. do we want to start testing against an astropy version before it gets announced? we only announce when it's on anaconda, but it may not be straight away, etc.)
