### ISSUE TITLE
On Python 3.4, install pytest-astropy with pip

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#280]
I noticed the following in one of the affiliated package logs:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pytest-astropy -> pytest >=3.1 -> python 2.7*
  - python 3.4*
```

It then proceeds to install astropy and other dependencies with pip. We should probably explicitly install pytest-astropy with pip on Python 3.3 and 3.4?

**Comment by bsipocz** [comment]
yes, or not install it at all as it isn't required for LTS and v3.0 astropy isn't working on these python versions anyway.

**Comment by bsipocz** [comment]
Closing this as python 3.4 reached its EOL, and thus very unlikely we come back to this to debug.
