### ISSUE TITLE
Experiment with the docker on travis

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#302]
This is not particularly a ci-helpers issue, but in general in astropy we need to look into the details of docker support with travis and whether we want to use it. And if yes, we will need to figure out the best way to do it: https://docs.travis-ci.com/user/docker/

**Comment by astrofrog** [comment]
Note that there is a ``continuumio/miniconda3`` docker image

**Comment by bsipocz** [comment]
Unlikely that this ever going to happen. Closing.
