### ISSUE TITLE
Weird issue with CONDA_ENVIRONMENT

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#309]
I'm running into an issue where the output from the conda command to set up the environment with ``CONDA_ENVIRONMENT`` doesn't appear unless I run with ``DEBUG=True``.

With DEBUG True: https://travis-ci.org/glue-viz/glue-jupyter/jobs/419855307

Without DEBUG: https://travis-ci.org/glue-viz/glue-jupyter/jobs/419850507

This is just a note to myself to investigate once I have time...

**Comment by bsipocz** [comment]
I don't think we use `CONDA_ENVIRONMENT` in many places, so it very likely can have bugs...
