### ISSUE TITLE
Update needed for Python 3.7 compatibility with available conda version

### ISSUE THREAD

**Issue by mperrin** [astropy/ci-helpers#312]
Several packages are now experiencing broken Travis builds, terminating with this error: 
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda==4.3.34
  - conda[version='>=4.5.11']
```
The problem appears to be due to upstream `miniconda3-latest` now defaulting to Python 3.7 with base conda version = 4.5.11. This conflicts with the statement in setup_dependencies_common.sh that pins conda to 4.3.34. 

ci-helpers probably ought to either not try to force conda to 4.3.34, or should depend on an earlier version of miniconda3 rather than miniconda3-latest. 

Thanks to @jhunkeler for helping to diagnose this one.

**Comment by eteq** [comment]
A temporary workaround is to manually set `CONDA_VERSION` to the latest (4.5.11 right now).  The PR to actually get this all working is #308

**Comment by mperrin** [comment]
Manually setting the `CONDA_VERSION` does fix this, yes. Thanks!
