### ISSUE TITLE
Hack to skip CI for CircleCI

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#321]
No sure where is the best place for https://github.com/astropy/astropy/pull/7815#issuecomment-421017419 to go. cc @Cadair

**Comment by bsipocz** [comment]
circleCI is currently not supported by ci-helpers, so it'll take a while if we need to implement this ourselves ;)

**Comment by bsipocz** [comment]
I close this now as a "wont fix" as we don't do circleCI here, and it's not clear that we'll ever do. Revisit is that changes.
