### ISSUE TITLE
Determine whether sip workaround for Windows is still required

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#346]
We should check if the following hack is still required:

https://github.com/astropy/ci-helpers/blob/4303c636b30f1704dd65521ac37baf0d13b85207/appveyor/install-miniconda.ps1#L401

This is now causing issues for some packages that use PyQt that need a more recent version of sip.

**Comment by bsipocz** [comment]
it's also pinned for travis, I suppose that can be removed around the same time as this one?
