### ISSUE TITLE
Consider updating miniconda version

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#353]
4.5.11 now comes with python3.7 and as we use that as default more and more places it would make sense to avoid one more python install.

**Comment by djhoese** [comment]
I was just about to make an issue for this, but conda 4.6 is available (not through miniconda installer yet). More importantly 4.6.3 fixes an issue where package "activation" scripts are now run after the package is installed. Without this packages like pyproj don't have their environment variables set correctly unless you deactivate and reactivate the test environment.

Would it be possible to include a `conda update conda` command in `ci-helpers`? See https://github.com/conda-forge/pyproj-feedstock/issues/29 for details.

**Comment by bsipocz** [comment]
You can have any conda version number you like, just use `CONDA_VERSION` in the travis config.

**Comment by djhoese** [comment]
Is that documented somewhere? I don't see it in the README?

**Comment by djhoese** [comment]
Also is there a way to say "the latest version"?

**Comment by bsipocz** [comment]
Hmm, there are missing pieces here and there. If you have time to open a PR, it would be more than welcome for both the README and the latest version. 

E.g. changing the logic to something like:
```
if [[ -z $CONDA_VERSION ]]; then
    CONDA_VERSION=4.5.12
elif [[ $CONDA_VERSION == latest ]] || [[ $CONDA_VERSION == stable ]]; then
    CONDA_VERSION=
fi
```
