### ISSUE TITLE
Segmentation fault in ci-helpers on travis

### ISSUE THREAD

**Issue by mhvk** [astropy/ci-helpers#356]
Not sure at all this is due to `ci-helpers`, but I am getting a repeatable segmentation fault in my travis docs-building test on a line from `ci-helpers`: https://travis-ci.org/mhvk/baseband/jobs/462022860#L1108

**Comment by bsipocz** [comment]
It's indeed coming from `ci-helpers`, but I really don't see why the mpl install messed up this much.

It's a long shot, but as the first try, could you try to use `PYTEST_VERSION='<3.10'`

**Comment by mhvk** [comment]
Sadly, that didn't do it (seehttps://travis-ci.org/mhvk/baseband/builds/462301398?utm_source=github_status&utm_medium=notification).

I'm also in the process of trying to make the python3 version of the package (which has an updated astropy helpers), but that did not help either: https://travis-ci.org/mhvk/baseband/jobs/462300902

**Comment by bsipocz** [comment]
It should be something totally unrelated you `baseband`, and rather a conda/mpl/other package issue. Maybe this is the resurfacing of the `sip`/`mpl` issue that we thought in https://github.com/astropy/ci-helpers/pull/349 is not relevant any more?

Could you try to add `sip<4.19` to `CONDA_DEPENDENCIES` for the failing build?

**Comment by mhvk** [comment]
Yes, that does it! Now trying without the pytest part. Experiments in https://github.com/mhvk/baseband/pull/295

**Comment by mhvk** [comment]
Yes, the sip version alone does it.

**Comment by mhvk** [comment]
I wonder if on travis we cannot replace more of conda (or all of it) with items from the Ubuntu distribution...
