### ISSUE TITLE
Add WARNING catching tests (to emulate build_sphinx tests)

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#36]
Most of the packages catch the docs build warnings and get failing the build status on travis if there are any of them. We need to reproduce that here, and see whether any `WARNING`s can come out of the install process.
(See this astropy build on the v1.0.x branch https://travis-ci.org/astropy/astropy/jobs/100148639#L362)

**Comment by astrofrog** [comment]
If the warnings are being written to stderr then we can do something like

```
source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh 2> warnings.log
test ! -s warnings.log
```
