### ISSUE TITLE
Consider unsetting bash errexit flag

### ISSUE THREAD

**Issue by djhoese** [astropy/ci-helpers#363]
This issue comes after some debugging with the Travis CI community here: https://travis-ci.community/t/build-fails-with-no-obvious-reason/1452

I've had multiple projects have failing jobs where the log shows that the job suddenly stopped (ex. https://travis-ci.org/ssec/polar2grid/jobs/468178261). As mentioned at the link above the reason the job stopped suddenly is because ci-helpers is setting `set -e` [here](https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L5). Since ci-helpers has to be sourced this setting is carried on after ci-helpers, in to the rest of the travis environment.

In my case, I had some issues in my sphinx docs `make html` (failing to find latex for building math formulas) and this was taken by travis/bash to be a failure and the script/environment exited immediately. Or at least that's what it looks like to me. I've gotten around this by doing `set +e` after sourcing ci-helpers in my `install` section, but maybe it could be done at the end of the `setup_dependencies_common.sh` script before exiting? Thoughts?

**Comment by djhoese** [comment]
Forgot to add this travis doc that was linked in the community discussion: https://docs.travis-ci.com/user/common-build-problems/#my-build-fails-unexpectedly

**Comment by bsipocz** [comment]
By all means open a PR for making it opt-out.

Also, maybe we could revise running the script vs sourceing it (given this commen `Note that using set -e in external scripts does not cause this problem, as the errexit is effective only in the external script.` the prior may be preferred). It's a much bigger overtake though to make sure everything keeps working as they are now atm.

**Comment by djhoese** [comment]
Unless conda has changed things recently, how would you get around sourcing conda? Or would that maybe be a separate step?

Asfor the "fix" for this, would you be open to me putting a `set +e` at the bottom of the `setup_dependencies_common.sh` script? The idea being that the one who modifies the global state should be the one to return it to its previous state.

**Comment by bsipocz** [comment]
Ah, OK, that sounds even better than an opt out option at the top.
`set +e` at the bottom seems sensible, and honestly looks like an oversight rather than a conscious decision of not having it.

**Comment by djhoese** [comment]
Ah it looks like this is a bug and was attempted already: https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L751

I don't see a `set -x` in the script but there is a `set +x` at the bottom. I'm guessing this was meant to be `set +e`?

**Comment by bsipocz** [comment]
`set -x` used to be at the top of this file, but then moved a but up to the `setup_conda.sh` script.

**Comment by djhoese** [comment]
Do you want `set -x` to remain in the common file or should it be removed since it is redundant in the current preferred installation method (`setup_conda.sh`)?
