### ISSUE TITLE
TST: Appveyor CI is broken

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#369]
Appears to have some sort of HTTP error in the first job (PY2), causing the rest to be cancelled. The CI history shows same error for different PRs, suggesting that this is a real problem with Appveyor CI for this repo, not caused by the individually unrelated PRs.

**Comment by pllim** [comment]
I submitted a ticket to Appveyor. 🤞

**Comment by bsipocz** [comment]
Actually I don't get it why we only see this issue on ci-helpers, but not in other repos?

**Comment by pllim** [comment]
I don't get it either. Appveyor help desk person asked me to rebuild the last successful one, so I am rebuilding the last successful merge run: https://ci.appveyor.com/project/Astropy/ci-helpers/builds/20919272 as https://ci.appveyor.com/project/Astropy/ci-helpers/builds/21420151 .

**Comment by pllim** [comment]
So... Did anyone change the Appeyor CI or relevant repo webhook settings around 20 days ago, when it was last successful?

**Comment by bsipocz** [comment]
No, not that I recall. The last touch of the both appveyor.yml or the appveyor dir was 27 days ago, and that one passed, and I can't recall changing anything on the appveyor site either.

**Comment by pllim** [comment]
**Reply from Appveyor Help Desk**

From: Ilya Finkelshteyn (Support staff)

I think that problem is related to the fact that you use outdated builds worker image.

https://github.com/astropy/ci-helpers/blob/b9703dd10f232a4ee40acafa9f11671c23e7ec6f/appveyor.yml#L76

I forked your repo, removed image setting and unneeded matrix dimensions (for fast test). As you see build completed OK (https://ci.appveyor.com/project/IlyaFinkelshteyn/ci-helpers/builds/21422410).
I would speculate that outdated image might not support some SSL protocols or ciphers Anaconda server started recently require. Best route here is to switch to standard build worker image, e.g. simple remove that line. If you have some string reason to stay with that image, we will think of other workarounds.

**Comment by pllim** [comment]
Possible fix at #377.

**Comment by bsipocz** [comment]
Ohh, you're awesome @pllim for tracking this done. Apparently we've moved away from this old image in https://github.com/astropy/astropy/issues/7683 for astropy, thus we haven't run into it elsewhere...

**Comment by pllim** [comment]
Credit goes to Ilya Finkelshteyn from Appveyor. 😄
