### ISSUE TITLE
Do we really need CI passing as "required"?

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#372]
I can see the benefit of this option, but it prevents PRs from being merged when `[ci skip]` is consciously provided, say, for a simple wording change in README.

**Comment by bsipocz** [comment]
We tried to play it super safe here, but I'm up for changes. @astrofrog?

**Comment by bsipocz** [comment]
(also, I don't have access to the settings, so my plan to sneakily merge these latest 3 PRs is failed).

**Comment by astrofrog** [comment]
I'm fine with changing the settings as long as we are actually very careful about when we merge things.

**Comment by bsipocz** [comment]
I'm a bit hesitant to lift the "base have to be up-to-date" as a PR can pass everything with an older master etc. So the current solution looks like a good compromise (we have to go to the settings to override the protection, but that means we're absolutely certain merging will be fine).

**Comment by astrofrog** [comment]
Ok sounds good, so I'll close this.

**Comment by pllim** [comment]
Yes, I think this is not as much a problem anymore now that @bsipocz has The Powers ™️ .
