### ISSUE TITLE
pytest souldn't be updated when PYTEST_VERSION is set

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#384]
PYTEST_VERSION is set to 2.8 here, yet 4.1 is installed which shouldn't not happen, even when the package itself requires pytest>=3. 
I run into this issue here first: https://github.com/astropy/pytest-doctestplus/pull/46

https://travis-ci.org/astropy/pytest-doctestplus/jobs/483920323

**Comment by weaverba137** [comment]
I saw a similar problem when trying to set `SPHINX_VERSION`.  Here is the test: https://travis-ci.org/weaverba137/pydl/jobs/525380465

`SPHINX_VERSION=1.8.5` but 2.0.1 was installed.  The test has `DEBUG=True`, and there are several places where the conda-meta/pinned file is shown, but I don't see sphinx in any of them, although I do see sphinx-astropy.
