### ISSUE TITLE
Help debugging hanging OSX environment

### ISSUE THREAD

**Issue by djhoese** [astropy/ci-helpers#391]
The aggdraw project has its travis jobs set up to use ci-helpers in one set of environments and cibuildwheel. For some reason on the OSX environments using ci-helpers the job hangs when loading/setting up ci-helpers. However, this **only** happens with a cron job. Any ideas? Any help would be appreciated.

Travis job: https://travis-ci.org/pytroll/aggdraw/jobs/525386141
Travis config: https://github.com/pytroll/aggdraw/blob/master/.travis.yml
Travis ci-helpers install script: https://github.com/pytroll/aggdraw/blob/master/ci/travis-install.sh

**Comment by bsipocz** [comment]
This is weird, and I cannot recall seeing it before. 
Also not clear why your last osx job succeeded. 

I would suggest try to reach out to travis support, maybe they will be able to give a useful insight.

**Comment by djhoese** [comment]
FYI I've created a topic about this here: https://travis-ci.community/t/job-hangs-but-only-when-run-from-cron/3593
