### ISSUE TITLE
Python version incorrect when using language: generic

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#394]
In https://github.com/astropy/reproject/pull/172 I noticed some bizarre behavior - if ``language: generic`` and ``PYTHON_VERSION`` is set in the global variables, but some jobs then opt to using ``python: 3.6``, the global ``PYTHON_VERSION`` is still picked up by ci-helpers.

**Comment by bsipocz** [comment]
Oh, I suppose we never wanted to rely on the `python: 3.6` nomenclature, saying that we install everything by conda anyway so don't rely on the prepopulated python VM.

**Comment by astrofrog** [comment]
Oh I see, if ``PYTHON_VERSION`` is defined it takes precedence: https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L97

**Comment by bsipocz** [comment]
This should be mentioned in the readme, otherwise I don't see a todo item codewise.
