### ISSUE TITLE
Should [docs only] skip PEP 8 check too?

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#404]
Currently, when `[docs only]` directive is given, everything but the doc build is skipped. However, why not check for PEP 8 anyway?

**Comment by bsipocz** [comment]
Didn't see it as a case when it was implemented, but I wouldn't be against a PR if you have preferences otherwise.

**Comment by pllim** [comment]
@bsipocz , looking at the script, I think it is a bug that it does not run PEP 8 check when `[docs only]` is provided. This is because the script only search `SETUP_CMD`, whereas the command is actually in `MAIN_CMD`. I proposed a patch at #407 , but please double check its logic.
