### ISSUE TITLE
`latest` MINICONDA_VERSION is not recognized for windows for Travis

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#406]
`travis/setup_conda_windows.sh` needs a bit of love and care to make this work. I label it as a bug as `latest` works for all other platforms.

cc @djhoese

**Comment by pllim** [comment]
Maybe this issue will fix itself when we move to Azure and not need `ci-helpers` altogether? :grimacing:

**Comment by bsipocz** [comment]
I have the feeling that this will be done before that, maybe next weekend 😬 I have to say, I rather like how I didn't open up the laptop in the past few weekends, but on the next one now really have to finish up a few threads here and there.

**Comment by djhoese** [comment]
I'm coming back to this after the various big-scale PRs were merged. I noticed that Windows on Travis defaults to miniconda 4.6. Choco now has 4.7, could this be made the new default (https://chocolatey.org/packages/miniconda3/4.7.10)?

What needs to be done to make MINICONDA_VERSION work in the scripts? What is wrong now?

**Comment by bsipocz** [comment]
> What needs to be done to make MINICONDA_VERSION work in the scripts? What is wrong now?

I can't recall the details, but I got bogged down with some windows path related issue. Now that the big refactor is in, I suspect it'll be much easier to come back to and use the examples both of you have cooked up.
