### ISSUE TITLE
Revise  [docs only] for repos that use circleCI for their docs build

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#417]
Jobs shouldn't be run tests here:
https://travis-ci.org/astropy/astropy/builds/586132358?utm_source=github_status&utm_medium=notification

Also, now that many projects are moving their docs builds to circleCI from travis, `[docs only]` could be made a bit more clever, e.g. if there isn't even one docs job in the travis config the hole build should be cancelled without going into the individual jobs.

**Comment by pllim** [comment]
Yeah, something like not right with this logic somehow but my bash-fu is not strong enough...

https://github.com/astropy/ci-helpers/blob/e1bddf10a07e88f571ea7e382051b5cab6fc4ee4/travis/setup_conda.sh#L49-L54

It looks as if `[docs only]` has *no effect* now; i.e., all the Travis jobs run regardless.

**Comment by pllim** [comment]
Maybe I broke it in #407 . :sob:

**Comment by pllim** [comment]
I think this is now fixed?

**Comment by pllim** [comment]
Oh, wait... Haven't done "if there isn't even one docs job in the travis config the hole build should be cancelled without going into the individual jobs"... BUT do we really want that? I thought we still want PEP 8 job to run regardless.

**Comment by bsipocz** [comment]
There is a pep8 test on circleCI now, too, so it's all good to cancel the whole of travis.

**Comment by pllim** [comment]
But, only the core does that, not everyone else who uses `ci-helpers`?

**Comment by bsipocz** [comment]
oh, yes, you're right regarding that.

**Comment by pllim** [comment]
Maybe the title of the issue should at least be updated, as `[docs only]` is no longer broken.
