### ISSUE TITLE
Pinning packages version number to aviod upgrade

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#42]
We had the issue that we coundn't fix the mpl version number to ``1.5.0`` in the photutils docs builds (https://github.com/astropy/photutils/pull/318) as it always got upgraded.

The upgrade is due to https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L106 where mpl isn't inheriting the fixed version number.

We can have temporary workarounds like #41, or introduce version number enviroment variables (like we have for astropy and numpy alread) for all the packages that get installed as an instrastructural dependency (like sphinx and matplotlib).

However it may be the best to pin the version numbers of all the packages that are listed with a required version number in ``CONDA_DEPENDENCIES``. I have a half baked hack for this, and will open a PR once I manage to get it work.

cc: @larrybradley @astrofrog

**Comment by larrybradley** [comment]
Thanks, @bsipocz.  In the long run, I agree it's probably better to allow setting (or overriding) the versions of any of the packages automatically installed in `setup_dependencies_common.sh` (e.g. `matplotlib`, `Sphinx`, `coveralls`, `Cython`, `jinja2`, `pytest-xdist`, `psutil`).

**Comment by bsipocz** [comment]
@larrybradley - Just as a follow up, now all packages can use a $PACKAGENAME_VERSION to override any version restrictions listed in either CONDA_DEPENDENCIES or indeed conda installed anywhere in ``setup_dependencies_common.sh``.

**Comment by larrybradley** [comment]
Thanks, @bsipocz!
