### ISSUE TITLE
Conda update 4.8.0

### ISSUE THREAD

**Issue by IshaniN** [astropy/ci-helpers#433]
Hey! I am new to coding and recently installed Anaconda and tried combining it with gurobi. It asked for an update to 4.8, and as soon as I updated the command conda was not recognized. What should I do? 

(base) C:\Users\Dell>conda --version
conda 4.7.12

(base) C:\Users\Dell>conda config --add channels http://conda.anaconda.org/gurobi

(base) C:\Users\Dell>conda install gurobi
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Dell\Anaconda3

  added / updated specs:
    - gurobi

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.0                |           py37_1         2.8 MB
    gurobi-9.0.0               |           py37_0        31.3 MB  gurobi
    ------------------------------------------------------------
                                           Total:        34.1 MB

The following NEW packages will be INSTALLED:

  gurobi             gurobi/win-64::gurobi-9.0.0-py37_0

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.8.0-py37_1

Proceed ([y]/n)? y

Downloading and Extracting Packages
gurobi-9.0.0         | 31.3 MB   | ############################################################################ | 100%
conda-4.8.0          | 2.8 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: | The batch file cannot be found.
The batch file cannot be found.

(base) C:\Users\Dell>conda update --yes --quiet conda
'conda' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\Dell>conda --version
'conda' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bsipocz** [comment]
@IshaniN - This repository is for continuous integration. For conda related issues, you may want check out this repository: https://github.com/conda/conda/
