### ISSUE TITLE
Fix or ditch appveyor

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#454]
The appveyor CI got broke down quite badly in the past month. 

I would be inclined to pull the plug, as we already planned, but first we need to check how many active projects still use it.  It maybe just a false impression that many have already moved on to travis or azure to do windows testing.

**Comment by astrofrog** [comment]
I would vote for ditch - we could keep the script and print out an error message recommending alternatives?

**Comment by pllim** [comment]
👍 to ditch. Adding a `os: windows` in `.travis.yml` isn't that hard.
