### ISSUE TITLE
Consider using micromamba

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#458]
Micromamba is the mamba equivalent of miniconda (see https://github.com/mamba-org/mamba#micromamba). We could imagine adding new ``setup_mamba*`` scripts which would set things up exclusively as opposed to using mamba just for installing as in #457. I imagine this could speed things up a bit. Because the scripts would be separate (except for the main one that sets up dependencies etc) this would be opt-in.

One limitation is that it looks like micromamba is not yet available for Windows (@wolfv, is that something that might exist in future?)

**Comment by wolfv** [comment]
yes, I think we'll have a Windows build at the end of the week. I have just added `vcpkg` to conda-forge that we can use to bootstrap the static library dependencies of micromamba on Windows.

**Comment by astrofrog** [comment]
Great, thanks!
