### ISSUE TITLE
ROADMAP: Move pip pinnings and archive repo

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#468]
1. Move pip pinnings somewhere else.
2. Close all open issues as won't fix.
3. Archive repo.
4. Send out a memo to astropy-dev mailing list.

c/c @astropy/coordinators

**Comment by astrofrog** [comment]
We should maybe also print out a big banner in the logs of Travis and AppVeyor to mention the deprecation.

**Comment by pllim** [comment]
It has been 4 years. Can we finally archive?

**Comment by pllim** [comment]
Do people still use this "pip pinning"?

**Comment by pllim** [comment]
If people still need pip pinning, we can still move it after the fact. Archiving now. Thanks, all!
