### ISSUE TITLE
Failing travis-ci builds

### ISSUE THREAD

**Issue by cdeil** [astropy/ci-helpers#47]
Since today, there's conda install issues in the Gammapy builds:
https://travis-ci.org/gammapy/gammapy/jobs/103558898

This error mentioning `gawk` is present in Astropy core and Gammapy builds:
https://travis-ci.org/astropy/astropy/jobs/103553616#L181

cc @bsipocz

**Comment by bsipocz** [comment]
Thanks @cdeil. There are so many resurfacing corner cases of #43 that I start to believe it was a spiky monster.

**Comment by bsipocz** [comment]
Second problem of missing gawk on osx is trivial and I already have the fix, however the first one is a bit more tricky.
Bash doesn't allow hyphens in variable names, thus we shouldn't really expect to have ``SCIKIT-IMAGE_VERSION`` like names either. I think the workaround would be to change all hyphens from conda names to underscores, and look for those variables instead.

@astrofrog - Do you think it's a reasonable solution, or should I try to come up with something else to make the hyphened version work?

**Comment by astrofrog** [comment]
@bsipocz - yes, that is a reasonable solution.
