### ISSUE TITLE
Make AppVeyor recognize the same set of environment variables as Travis

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#5]
Low priority, but would be nice in future to avoid having two sets of instructions.

**Comment by bsipocz** [comment]
I'm not sure how feasible this is, we already have some variable that only makes sense for travis (e.g. EVENT_TYPE). 
However most of the common ones are recognized by appveyor, too.

I'm proposing to close this issue, and rather open new ones for each of the missing variables that should work on appveyor but not yet implemented, it will be easier to incrementally add them.

**Comment by bsipocz** [comment]
This won't happen any more, was  a "nice" catch game over the year, but we never really got there. 
Travis now has windows support, switch to it to get the same functionality.
