### ISSUE TITLE
Add option to remove ``-q`` flag for conda

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#50]
In some cases, people might want to not have conda builds be quiet, so maybe we can add an env variable (or simply re-use ``$DEBUG``) to indicate that we want verbose output from conda.

**Comment by bsipocz** [comment]
Either way is fine by me, although I'm a bit inclined to reuse DEBUG and put this into that, too.

**Comment by bsipocz** [comment]
Done in #53
