### ISSUE TITLE
Specifying CONDA_DEPENDENCIES vs environment variables

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#52]
The new system of specifying package versions via environment variables works nicely. However, there is a small difference in behavior between specifying them via environment variables and via the ``CONDA_DEPENDENCIES``, i.e.

```
MATPLOTLIB_VERSION=1.3
```

vs

```
CONDA_DEPENDENCIES='matplotlib=1.3'
```

The first case results in the pinned file containing

```
matplotlib 1.3*
```

and the second:

```
matplotlib ==1.3
```

I think that the second case should also be changed to mean ``1.3*``, because that's normally how it works if we do ``conda install matplotlib=1.3`` (1.3.1 could be installed)

**Comment by bsipocz** [comment]
Done in #53.
