### ISSUE TITLE
Add option of skipping/running a subset of builds

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#73]
Based on this conversation https://github.com/astropy/astropy/pull/4556#issuecomment-194059021 (copied below), we may add an option of either skip (or run) a subset of the travis builds when there is a string pattern in the commit message.

 I'm not sure which approach is better, given that many times even `[ci skip]` is not used optimally. However before implementing anything, we need to decide whether this is needed, and which approach (run or skip) to go with (or can do both).

> > mhvk commented 12 hours ago
> > Agreed that we should not build both! Indeed, in principle, I think it would be nice to reduce the tests run for PRs to a smaller subset, and only run a full suite before actual merging. But not sure that is possible (and easy).
> 
> bsipocz commented 11 hours ago
> I think it shouldn't be too difficult to add an env variable to ci-helpers that makes sure that the tests are only run when the commit message contains a certain keyword (e.g. Merge pull request (as that is included in all PR merge, or something like [full tests] or [full suite], etc).

I'm cc-ing for brainstorming whoever may be interested in this for astropy and other packages.
 @astrofrog @mhvk @eteq @cdeil @Cadair

**Comment by astrofrog** [comment]
We could have builds that run only on master, and for that all we could do is have a flag ``MASTER_ONLY=True`` that we can set for certain builds. Then, we can try and exit as soon as we can if the active branch is not master, and just pass the build?
