### ISSUE TITLE
Travis builds can't find libgfortran even though it is installed.

### ISSUE THREAD

**Issue by weaverba137** [astropy/ci-helpers#74]
Lately I have been seeing Travis builds failing because:

```
E   ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

For example: https://travis-ci.org/weaverba137/pydl/jobs/115556329

My [.travis.yml file](https://github.com/weaverba137/pydl/blob/master/.travis.yml) includes:

```
- CONDA_DEPENDENCIES='libgfortran scipy matplotlib'
```

and the output of `source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh` appears to show that libgfortran is installed.

Any help would be appreciated.

**Comment by weaverba137** [comment]
I did this:
```
- CONDA_DEPENDENCIES='libgfortran=1.0 scipy matplotlib'
```
and that solved the problem, but this is still mildly annoying & non-obvious that I would have to do that, based on the ci-helpers and package-template documentation.

**Comment by astrofrog** [comment]
@weaverba137 - what happens if you do ``CONDA_DEPENDENCIES='nomkl libgfortran scipy matplotlib'``? I suspect this is a problem on the conda side, but it would help to know if it's linked to the new MKL packages.

**Comment by weaverba137** [comment]
That *did not* work.

Also there's an interesting pattern, which occurs with or without `nomkl`: tests fail on Python 2.7 & 3.4, but pass on 3.3, even though the logs show that libgfortran 3.0 is being installed in all three cases.

**Comment by weaverba137** [comment]
I think this issue applies to Anaconda configurations from a long time ago.
