### ISSUE TITLE
Testing affiliated packages that require scipy in Python 3.5

### ISSUE THREAD

**Issue by weaverba137** [astropy/ci-helpers#80]
This issue was originally reported on astropy/package-template#165, but it was recommended to move it here.

I'd like to be able to run Travis tests in Python 3.5, but currently there is a package compatibility issue in anaconda that prevents the installation of scipy, which my package requires.

Below is a snippet of the Travis log for a recent build, showing the incompatibility report. [You can also view the full log.](https://travis-ci.org/weaverba137/pydl/jobs/126795077)

```
The following specifications were found to be in conflict:
  - matplotlib -> numpy 1.9*
  - matplotlib -> python 2.6*|2.7*|3.3*|3.4*
  - numpy 1.9* -> python 2.6*|2.7*|3.3*|3.4*
  - pip (target=pip-8.1.1-py35_1.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*
  - py (target=py-1.4.31-py35_0.tar.bz2) -> python 2.6*|2.7*|3.2*|3.3*|3.4*|3.5*
  - pytest (target=pytest-2.9.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.2*|3.3*|3.4*|3.5*
  - python 3.5*
  - scipy 0.14* -> numpy 1.9*
  - scipy 0.14* -> python 2.6*|2.7*|3.3*|3.4*
  - setuptools (target=setuptools-20.7.0-py35_0.tar.bz2) -> python 2.6*|2.7*|3.2*|3.3*|3.4*|3.5*
  - wheel (target=wheel-0.29.0-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by astrofrog** [comment]
Are you specifically requiring Numpy 1.9?

**Comment by weaverba137** [comment]
No, that's just the version I grabbed from package-template the last time I updated it.

**Comment by astrofrog** [comment]
@weaverba137 - do you see the same issue if you set ``NUMPY_VERSION=stable``?

**Comment by weaverba137** [comment]
Actually, that makes the problem worse, because there is no `SCIPY_VERSION=stable`.

**Comment by astrofrog** [comment]
@weaverba137 - ah, but only do that for Numpy. For scipy, try not specifying a version at all.

**Comment by weaverba137** [comment]
That appears to have done the trick, though it is still necessary to specify `libgfortran=1.0` for the specific combination Python/2.7, numpy/1.9, scipy/0.14.

**Comment by weaverba137** [comment]
I consider this solved.
