### ISSUE TITLE
Make sure version pinning works for numpy and astropy when in CONDA_DEPENDENCIES

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#84]
They are not designed to be listed in `CONDA_DEPENDENCIES` and if one of the string versions were used in e.g. `ASTROPY_VERSION`, the version pinning fails the build.

This issue came up with https://github.com/Chandra-MARX/marxs/pull/62, here is a travis log snippet:

```
++++CONDA_DEPENDENCIES='numpy scipy astropy cffi sphinx matplotlib'

++++[[ True == True ]]

++++cat /home/travis/miniconda/envs/test/conda-meta/pinned

numpy stable*

scipy

astropy stable*

cffi

sphinx

matplotlib

++++echo numpy scipy astropy cffi sphinx matplotlib

numpy scipy astropy cffi sphinx matplotlib

++++[[ stable == dev* ]]

++++[[ stable == stable ]]

++++conda install numpy

Fetching package metadata: ..........

Solving package specifications: .

Error:  Packages missing in current linux-64 channels: 

  - numpy stable*

  - astropy stable*
```

**Comment by astrofrog** [comment]
In the spirit of making ci-helpers more general for other packages, I think it should be fine to list astropy and numpy in CONDA_DEPENDENCIES, and I think in this case it might just be a matter of ignoring 'stable' in any pinning since it's equivalent to not pinning?

**Comment by astrofrog** [comment]
Ah but that won't work for dev - I see why it makes sense to not list them in CONDA_DEPENDENCIES

**Comment by bsipocz** [comment]
yes, and we already do that. Or I remember making this fix at some point.

**Comment by bsipocz** [comment]
Oh, it's not merged yet, https://github.com/astropy/ci-helpers/pull/124
Would you take a look at it?

**Comment by bsipocz** [comment]
@cdeil run into this issue again in https://github.com/hipspy/hips/issues/6

**Comment by astrofrog** [comment]
I ran into this again. I think that we should simply strip numpy and astropy out of CONDA_DEPENDENCIES if they are specified accidentally.

**Comment by bsipocz** [comment]
@astrofrog - sounds good. I don't have time this week to do any work on ci-helpers, but there are a few open issues I would rather see solved soon, so probably next week I can cook up a few fixes.

**Comment by astrofrog** [comment]
@bsipocz - great! This is not really urgent though, so don't worry too much if you don't have time :)
