### ISSUE TITLE
A failure in setting up the environment should stop the build

### ISSUE THREAD

**Issue by astrofrog** [astropy/ci-helpers#87]
In the following example:

https://ci.appveyor.com/project/Eric89GXL/vispy/build/1.0.1568

There is an issue with a download, but the build proceeds anyway. This should not be the case, but not sure how to change that?

**Comment by bsipocz** [comment]
Didn't we have the same problem with Travis? I can't find how we fixed it (or whether it is fixed at all, although at least conda exists when I try to install a nonexistent package).

**Comment by astrofrog** [comment]
It does ring a bell. I guess we could test by setting up a fake package and then adding a non-existent dependency in ``CONDA_DEPENDENCIES``.

**Comment by bsipocz** [comment]
It would be great to fix it, I spent quite a few minutes and an appveyor restart until spotted that the install section failed here:
https://ci.appveyor.com/project/Astropy/astroquery/build/1.0.389/job/g9jogre6e9s9125w#L116

**Comment by astrofrog** [comment]
Yeah, it's very frustrating and wastes build time. What about we just ask [here](https://github.com/appveyor/ci/issues) how to force a built to stop if a powershell command fails?

**Comment by bsipocz** [comment]
I have a vague memory of running into similar stuff recently, will try that first and if that doesn't work, open an issue.

**Comment by bsipocz** [comment]
Reopening as #197 pointed out that there are parts where this is not yet implemented.
