### ISSUE TITLE
Getting nagged to upgrade pip

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#91]
I got nagged by both Travis CI and Appveyor to upgrade to pip 8.1.2. Here is an example message from Appveyor:

```
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

On Travis, I am able to get rid of that message by doing:
```yaml
install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    - pip install --upgrade pip
```

But this does not work on Appveyor:
```yaml
install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    - "python -m pip install --upgrade pip"
```

I see that it updates `pip` but then it still complains about the old version:
```
Successfully installed astropy-1.2.dev15418
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
 
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
activate test
Deactivating environment "C:\conda"...
Activating environment "C:\conda\envs\test"...
python -m pip install --upgrade pip
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-8.1.2
```

Moving the upgrade command to *before* `git clone git://github.com/astropy/ci-helpers.git` also does not work.

Why am I getting these messages? Does `ci-helpers` set the pip version to 8.1.1 for some reason? Should there be extra command in `ci-helpers` to automatically upgrade `pip`?

**Comment by bsipocz** [comment]
@pllim - pip is installed using (mini)conda in ``ci-helpers``. They may not have the very latest at the given time, but I wouldn't worry about about the warning and just ignore it. Also don't see the point to manually update it in ``ci-helpers`` as I can't see any scenario where the result of the testing would depend on the version of pip.

So if you find it annoying, I suggest to do the upgrade as you did above, but also please use ``--no-deps``, too as it may mess up other packages by upgrading them too (though it shouldn't).

Not sure why appveyor still complains about the version though. Does the following also complain?
``- "%CMD_IN_ENV% pip install --upgrade --no-deps pip"``

As pip is installed in ``ci-helpers``, it's not possible to do the upgrade before the cloning.

**Comment by pllim** [comment]
@bsipocz , the command you provided did not work for me. I get "permission denied". But when I added `--user` to the command, I get "system cannot find the path specified".

**Comment by pllim** [comment]
Right now, it is 8.1.1 vs 8.1.2, so it's no big deal. But eventually, the default `pip` version should be upgraded.

**Comment by bsipocz** [comment]
Whenever the new one makes it way to conda, it will be used automatically.

**Comment by pllim** [comment]
Okay.
