### ISSUE TITLE
AppVeyor 3.5 failure

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ci-helpers#92]
I realized that the python 3.5 appveyor build seems to fail with "Error code 1" (see for example [here](https://ci.appveyor.com/project/Astropy/ccdproc-iqpau/build/1.0.187/job/5ax1bmjpuo5p3y2r#L129))

There was a new ``msvc_runtime`` build on conda (yesterday or tonight) and it seems likely that this is somehow connected. But I cannot reproduce it locally - maybe because I'm using mkl 11.3.3 and some other packages that aren't installed in AppVeyor - so I can't investigate it.

**Comment by astrofrog** [comment]
I think this could be related to https://github.com/conda-forge/staged-recipes/issues/666 - the fix is pinning the version and build of the runtime environment

**Comment by astrofrog** [comment]
I'm working on a fix in ci-helpers

**Comment by bsipocz** [comment]
Thanks @astrofrog for working on this!

**Comment by astrofrog** [comment]
@Cadair @MSeifert04 - should be fixed, try restarting builds

**Comment by bsipocz** [comment]
I've restarted the astropy and ccdproc ones.

**Comment by MSeifert04** [comment]
@bsipocz @astrofrog Thank you and it seems the PRs don't fail anymore (at least not with AppVeyor :smile:) 

FWIW - It seems the corrupt package was removed from conda. Before I close this issue as resolved I wanted to ask if fixing the version is still required.

**Comment by bsipocz** [comment]
@MSeifert04 - I tend to like keeping the workarounds in for a while in ci-helpers (at least until the corresponding upstream issues are closed with everyone being happy on the thread). 
I may be wrong here, but as I see our aim is to test the (astropy) packages and not whether the whole windows ecosystems works with the most cutting edge versions of everything.

**Comment by MSeifert04** [comment]
@bsipocz no problem from my side. I just thought the tests should be as "cutting edge" as possible to identify upcoming problems as soon as possible. Not catching the Bugs of other packages but their features or API changes. Feel free to close the issue.
